name: Demo Flow

on: 
  push: 
    branches: 
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore
        run: dotnet restore TodoApp/*.csproj

      - name: Build
        run: dotnet build TodoApp/*.csproj --configuration Release --no-restore

  deploy1:
    name: Deploy Job
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - run: | 
          echo "Deploying the application1..."
          echo "Deployment1 complete."

  deploy2:
    name: Deploy Job 2
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - run: | 
          echo "Deploying the application2..."
          echo "Deployment2 complete."

  post-deploy:
    name: Post-Deploy Job
    runs-on: ubuntu-24.04
    needs: [deploy1, deploy2]
    if: failure()
    steps:
      - run: | 
          echo "Running post-deployment tasks..."
          echo "Post-deployment tasks complete."