name: Demo Flow

on: 
  push: 
    branches: 
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:
      - run: | 
          echo "This is a demo workflow running on push, pull request, schedule, or manual trigger."
          echo "This is a demo workflow running on push, pull request, schedule, or manual trigger 2."
  deploy:
    name: Deploy Job
    runs-on: ubuntu-24.04
    steps:
      - run: | 
          echo "Deploying the application..."
          echo "Deployment complete."
